sudo: required
services:
  - docker
before_install:
  - docker build -t jonaskay/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true jonaskay/docker-react npm run test
deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "toto-docker-react"
  env: "TotoDockerReact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-766261213300"
  bucket_path: "toto-docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
